sudo: required
dist: trusty
language: generic
rvm:
  - 1.9.3
compiler:
  - gcc
env:
  global:
    - CATKIN_WS=~/catkin_ws
    - CATKIN_WS_SRC=${CATKIN_WS}/src
  matrix:
    - CI_ROS_DISTRO="jade" USE_GAZEBO6="true"
    - CI_ROS_DISTRO="indigo"
    - CI_ROS_DISTRO="indigo" USE_GAZEBO6="true"
matrix:
  allow_failures:
    - env: CI_ROS_DISTRO="jade" USE_GAZEBO6="true"
  
install:
# Typegen/Orogen Hack : reset the path so rosdep installs 1.9.3 correctly
  - export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
  - wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-rosdep python-catkin-tools
  - sudo apt-get install -qq -y ros-$CI_ROS_DISTRO-catkin ros-$CI_ROS_DISTRO-ros
  - sudo rosdep init
  - rosdep update
  - source /opt/ros/$CI_ROS_DISTRO/setup.bash
  - mkdir -p $CATKIN_WS_SRC
  - ln -s $TRAVIS_BUILD_DIR $CATKIN_WS_SRC
  - cd $CATKIN_WS
  - catkin init
  - cd $CATKIN_WS_SRC
  - git clone https://github.com/kuka-isir/rtt_gazebo
  - git clone https://github.com/kuka-isir/rtt_ros_kdl_tools
  - wget https://raw.githubusercontent.com/IDSCETHZurich/re_trajectory-generator/master/kuka_IK/include/friComm.h
  - mv friComm.h $CATKIN_WS_SRC/rtt_lwr/lwr_hardware/kuka_lwr_fri/include/kuka_lwr_fri/friComm.h
  - rosdep install -r --from-paths $CATKIN_WS_SRC/ --rosdistro $ROS_DISTRO -y
  - if [ -n "$USE_GAZEBO6" ] ; then sudo apt-get install -qq -y ros-indigo-gazebo6-ros-pkgs; fi
  - source /opt/ros/$CI_ROS_DISTRO/setup.bash

script:
  # Enable install space
  - catkin config --install
  # Build [and Install] packages
  - catkin build --limit-status-rate 0.1 --no-notify --no-status -j2 -DCATKIN_ENABLE_TESTING=OFF -DCMAKE_BUILD_TYPE=Debug
  # Build tests
  #- catkin build --limit-status-rate 0.1 --no-notify --make-args tests
  # Run tests
  #- catkin run_tests
