<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

   <xacro:property name="epingle_length" value="0.09" />
   <xacro:property name="epingle_radius" value="0.002" />
   <xacro:property name="motor_length" value="0.02" />
   <xacro:property name="motor_radius" value="0.025" />

   <xacro:macro name="head_cam">

     <link name="epingle_link" >
       <inertial>
         <origin xyz="0 0 0.5" rpy="0 0 0"/>
         <mass value="0.1"/>
         <inertia ixx="0.001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001" />
       </inertial>

       <visual name="motor">
         <origin xyz="0 0 0" rpy="0 0 0" />
         <geometry>
           <cylinder length="${motor_length}" radius="${motor_radius}" />
         </geometry>
       </visual>

       <visual name="epingle">
         <origin xyz="0 0 ${epingle_length/2.0}" rpy="0 0 0" />
         <geometry>
           <cylinder length="${epingle_length}" radius="${epingle_radius}" />
         </geometry>
       </visual>

       <collision name="motor_collision">
         <origin xyz="0 0 0" rpy="0 0 0" />
         <geometry>
           <cylinder length="${motor_length}" radius="${motor_radius}" />
         </geometry>
       </collision>

       <collision name="epingle_collision">
         <origin xyz="0 0 ${epingle_length/2.0}" rpy="0 0 0" />
         <geometry>
           <cylinder length="${epingle_length}" radius="${epingle_radius}" />
         </geometry>
      </collision>
    </link>

    <joint name="epingle_joint" type="fixed">
      <origin xyz="0 0 ${motor_length/2.0}" rpy="0 0 0"/>
      <parent link="ati_link"/>
      <child link="epingle_link"/>
    </joint>

	  <link name="cam_link" >
      <inertial>
        <origin xyz="${-0.045/2.0} ${-0.042/2.0} ${-0.032/2.0}" rpy="0 0 0"/>
        <mass value="0.1"/>
        <inertia ixx="0.001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001" />
      </inertial>

      <visual>
        <origin xyz="${-0.045/2.0} 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.045 0.042 0.032" />
        </geometry>
        <material name="Cyan">
          <color rgba="0 1.0 1.0 1.0"/>
        </material>
      </visual>

      <collision>
        <origin xyz="${-0.045/2.0} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.045 0.042 0.032" />
        </geometry>
      </collision>
	  </link>

    <link name="epingle_tip_link" />

    <joint name="ati_to_tip_joint" type="fixed">
      <origin rpy="${M_PI} 0 0" xyz="0 0 ${motor_length+epingle_length}" />
	    <parent link="ati_link" />
	    <child link="epingle_tip_link" />
	  </joint>

	  <joint name="ati_to_cam_joint" type="fixed">
	    <!--origin rpy="${M_PI} ${-M_PI/2.0+atan(0.1/(motor_length+epingle_length))} ${M_PI}" xyz="0.1 0 0" /-->
      	<origin rpy="${M_PI} -0.8329812666744316 ${M_PI}" xyz="0.1 0 0" />
	    <parent link="ati_link" />
	    <child link="cam_link" />
	  </joint>

    <link name="cam_link_optical" >
	  </link>

    <joint name="cam_optical_joint" type="fixed">
      <!-- these values have to be these values otherwise the gazebo camera
          image won't be aligned properly with the frame it is supposedly
          originating from -->
      <origin xyz="0 0 0" rpy="-1.570796 0 -1.570796"/>
      <parent link="cam_link"/>
      <child link="cam_link_optical"/>
    </joint>
   </xacro:macro>

</robot>
